stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher-demo
      pushRemote: true
      registry: index.docker.io
- name: Deploy image into cluster
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
