apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-deployment
  labels:
    app: rancher-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
      - name: rancher-demo
        image: zaitsxl/rancher-demo
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata: 
  name: rancher-demo-service
  labels: 
    app: rancher-demo
spec: 
  type: NodePort
  ports:
    - port: 12345
